# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    '''!@brief Klasa odpowiadająca za ustawienia GUI.
    
    Klasa w całości wygenerowana przez program Qt Designer.

    '''
    def setupUi(self, MainWindow):
        '''!@brief Metoda odpowiadająca za odpowiednią konfigurację GUI.
        
        '''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 621)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 751, 581))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.background = QtWidgets.QLabel(self.page)
        self.background.setGeometry(QtCore.QRect(10, 0, 741, 581))
        self.background.setStyleSheet("background-color: rgba(15, 30, 40, 240);\n"
"border-radius:20px;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.login = QtWidgets.QLineEdit(self.page)
        self.login.setGeometry(QtCore.QRect(160, 330, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgb(46, 82, 101);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.login.setText("")
        self.login.setObjectName("login")
        self.haslo = QtWidgets.QLineEdit(self.page)
        self.haslo.setGeometry(QtCore.QRect(160, 390, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.haslo.setFont(font)
        self.haslo.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgb(46, 82, 101);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;")
        self.haslo.setEchoMode(QtWidgets.QLineEdit.Password)
        self.haslo.setObjectName("haslo")
        self.logo = QtWidgets.QLabel(self.page)
        self.logo.setGeometry(QtCore.QRect(240, 0, 301, 311))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(300)
        font.setBold(False)
        font.setWeight(50)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.login_btn = QtWidgets.QPushButton(self.page)
        self.login_btn.setGeometry(QtCore.QRect(240, 470, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton#login_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#login_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#login_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.exit_btn = QtWidgets.QPushButton(self.page)
        self.exit_btn.setGeometry(QtCore.QRect(700, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("QPushButton#exit_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#exit_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#exit_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.exit_btn.setObjectName("exit_btn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.background_2 = QtWidgets.QLabel(self.page_2)
        self.background_2.setGeometry(QtCore.QRect(10, 0, 741, 581))
        self.background_2.setStyleSheet("background-color: rgba(15, 30, 40, 240);\n"
"border-radius:20px;")
        self.background_2.setText("")
        self.background_2.setObjectName("background_2")
        self.exit_btn_2 = QtWidgets.QPushButton(self.page_2)
        self.exit_btn_2.setGeometry(QtCore.QRect(700, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setStyleSheet("QPushButton#exit_btn_2{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#exit_btn_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#exit_btn_2:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.logout_btn = QtWidgets.QPushButton(self.page_2)
        self.logout_btn.setGeometry(QtCore.QRect(650, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logout_btn.setFont(font)
        self.logout_btn.setStyleSheet("QPushButton#logout_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#logout_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#logout_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.logout_btn.setObjectName("logout_btn")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(170, 40, 20, 511))
        self.line.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.menu_label = QtWidgets.QLabel(self.page_2)
        self.menu_label.setGeometry(QtCore.QRect(30, 0, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.menu_label.setFont(font)
        self.menu_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.menu_label.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_label.setObjectName("menu_label")
        self.chart_btn = QtWidgets.QPushButton(self.page_2)
        self.chart_btn.setGeometry(QtCore.QRect(30, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chart_btn.setFont(font)
        self.chart_btn.setStyleSheet("QPushButton#chart_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#chart_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#chart_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.chart_btn.setObjectName("chart_btn")
        self.history_btn = QtWidgets.QPushButton(self.page_2)
        self.history_btn.setGeometry(QtCore.QRect(30, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.history_btn.setFont(font)
        self.history_btn.setStyleSheet("QPushButton#history_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#history_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#history_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.history_btn.setObjectName("history_btn")
        self.settings_btn = QtWidgets.QPushButton(self.page_2)
        self.settings_btn.setGeometry(QtCore.QRect(30, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet("QPushButton#settings_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#settings_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#settings_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.settings_btn.setObjectName("settings_btn")
        self.stany_czujnikow_label = QtWidgets.QLabel(self.page_2)
        self.stany_czujnikow_label.setGeometry(QtCore.QRect(205, 0, 411, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.stany_czujnikow_label.setFont(font)
        self.stany_czujnikow_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.stany_czujnikow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stany_czujnikow_label.setObjectName("stany_czujnikow_label")
        self.temp_label = QtWidgets.QLabel(self.page_2)
        self.temp_label.setGeometry(QtCore.QRect(190, 100, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.sensor_btn = QtWidgets.QPushButton(self.page_2)
        self.sensor_btn.setGeometry(QtCore.QRect(200, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sensor_btn.setFont(font)
        self.sensor_btn.setStyleSheet("QPushButton#sensor_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#sensor_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#sensor_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.sensor_btn.setObjectName("sensor_btn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.background_3 = QtWidgets.QLabel(self.page_3)
        self.background_3.setGeometry(QtCore.QRect(10, 0, 741, 581))
        self.background_3.setStyleSheet("background-color: rgba(15, 30, 40, 240);\n"
"border-radius:20px;")
        self.background_3.setText("")
        self.background_3.setObjectName("background_3")
        self.exit_btn_3 = QtWidgets.QPushButton(self.page_3)
        self.exit_btn_3.setGeometry(QtCore.QRect(700, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_btn_3.setFont(font)
        self.exit_btn_3.setStyleSheet("QPushButton#exit_btn_3{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#exit_btn_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#exit_btn_3:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.exit_btn_3.setObjectName("exit_btn_3")
        self.logout_btn_2 = QtWidgets.QPushButton(self.page_3)
        self.logout_btn_2.setGeometry(QtCore.QRect(650, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logout_btn_2.setFont(font)
        self.logout_btn_2.setStyleSheet("QPushButton#logout_btn_2{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#logout_btn_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#logout_btn_2:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.logout_btn_2.setObjectName("logout_btn_2")
        self.line_2 = QtWidgets.QFrame(self.page_3)
        self.line_2.setGeometry(QtCore.QRect(170, 40, 20, 511))
        self.line_2.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.menu_label_2 = QtWidgets.QLabel(self.page_3)
        self.menu_label_2.setGeometry(QtCore.QRect(30, 0, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.menu_label_2.setFont(font)
        self.menu_label_2.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.menu_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_label_2.setObjectName("menu_label_2")
        self.back_btn = QtWidgets.QPushButton(self.page_3)
        self.back_btn.setGeometry(QtCore.QRect(30, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("QPushButton#back_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#back_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#back_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.wykresy_label = QtWidgets.QLabel(self.page_3)
        self.wykresy_label.setGeometry(QtCore.QRect(195, 0, 231, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.wykresy_label.setFont(font)
        self.wykresy_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.wykresy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wykresy_label.setObjectName("wykresy_label")
        self.chart_sensor = QtWidgets.QPushButton(self.page_3)
        self.chart_sensor.setGeometry(QtCore.QRect(200, 120, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chart_sensor.setFont(font)
        self.chart_sensor.setStyleSheet("QPushButton#chart_sensor{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#chart_sensor:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#chart_sensor:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.chart_sensor.setObjectName("chart_sensor")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.background_4 = QtWidgets.QLabel(self.page_4)
        self.background_4.setGeometry(QtCore.QRect(10, 0, 741, 581))
        self.background_4.setStyleSheet("background-color: rgba(15, 30, 40, 240);\n"
"border-radius:20px;")
        self.background_4.setText("")
        self.background_4.setObjectName("background_4")
        self.exit_btn_4 = QtWidgets.QPushButton(self.page_4)
        self.exit_btn_4.setGeometry(QtCore.QRect(700, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_btn_4.setFont(font)
        self.exit_btn_4.setStyleSheet("QPushButton#exit_btn_4{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#exit_btn_4:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#exit_btn_4:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.exit_btn_4.setObjectName("exit_btn_4")
        self.logout_btn_3 = QtWidgets.QPushButton(self.page_4)
        self.logout_btn_3.setGeometry(QtCore.QRect(650, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logout_btn_3.setFont(font)
        self.logout_btn_3.setStyleSheet("QPushButton#logout_btn_3{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#logout_btn_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#logout_btn_3:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.logout_btn_3.setObjectName("logout_btn_3")
        self.line_3 = QtWidgets.QFrame(self.page_4)
        self.line_3.setGeometry(QtCore.QRect(170, 40, 20, 511))
        self.line_3.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.menu_label_3 = QtWidgets.QLabel(self.page_4)
        self.menu_label_3.setGeometry(QtCore.QRect(30, 0, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.menu_label_3.setFont(font)
        self.menu_label_3.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.menu_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_label_3.setObjectName("menu_label_3")
        self.back_btn_2 = QtWidgets.QPushButton(self.page_4)
        self.back_btn_2.setGeometry(QtCore.QRect(30, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_btn_2.setFont(font)
        self.back_btn_2.setStyleSheet("QPushButton#back_btn_2{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#back_btn_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#back_btn_2:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.back_btn_2.setObjectName("back_btn_2")
        self.historia_label = QtWidgets.QLabel(self.page_4)
        self.historia_label.setGeometry(QtCore.QRect(205, 0, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.historia_label.setFont(font)
        self.historia_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.historia_label.setAlignment(QtCore.Qt.AlignCenter)
        self.historia_label.setObjectName("historia_label")
        self.browse_btn = QtWidgets.QPushButton(self.page_4)
        self.browse_btn.setGeometry(QtCore.QRect(220, 120, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browse_btn.setFont(font)
        self.browse_btn.setStyleSheet("QPushButton#browse_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#browse_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#browse_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.browse_btn.setObjectName("browse_btn")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.background_5 = QtWidgets.QLabel(self.page_5)
        self.background_5.setGeometry(QtCore.QRect(10, 0, 741, 581))
        self.background_5.setStyleSheet("background-color: rgba(15, 30, 40, 240);\n"
"border-radius:20px;")
        self.background_5.setText("")
        self.background_5.setObjectName("background_5")
        self.exit_btn_5 = QtWidgets.QPushButton(self.page_5)
        self.exit_btn_5.setGeometry(QtCore.QRect(700, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_btn_5.setFont(font)
        self.exit_btn_5.setStyleSheet("QPushButton#exit_btn_5{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#exit_btn_5:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#exit_btn_5:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.exit_btn_5.setObjectName("exit_btn_5")
        self.logout_btn_4 = QtWidgets.QPushButton(self.page_5)
        self.logout_btn_4.setGeometry(QtCore.QRect(650, 10, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.logout_btn_4.setFont(font)
        self.logout_btn_4.setStyleSheet("QPushButton#logout_btn_4{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#logout_btn_4:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#logout_btn_4:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.logout_btn_4.setObjectName("logout_btn_4")
        self.line_4 = QtWidgets.QFrame(self.page_5)
        self.line_4.setGeometry(QtCore.QRect(170, 40, 20, 511))
        self.line_4.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.menu_label_4 = QtWidgets.QLabel(self.page_5)
        self.menu_label_4.setGeometry(QtCore.QRect(30, 0, 131, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.menu_label_4.setFont(font)
        self.menu_label_4.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.menu_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_label_4.setObjectName("menu_label_4")
        self.back_btn_3 = QtWidgets.QPushButton(self.page_5)
        self.back_btn_3.setGeometry(QtCore.QRect(30, 120, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_btn_3.setFont(font)
        self.back_btn_3.setStyleSheet("QPushButton#back_btn_3{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#back_btn_3:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#back_btn_3:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.back_btn_3.setObjectName("back_btn_3")
        self.ustawienia_label = QtWidgets.QLabel(self.page_5)
        self.ustawienia_label.setGeometry(QtCore.QRect(195, 0, 291, 111))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.ustawienia_label.setFont(font)
        self.ustawienia_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.ustawienia_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ustawienia_label.setObjectName("ustawienia_label")
        self.progi_label = QtWidgets.QLabel(self.page_5)
        self.progi_label.setGeometry(QtCore.QRect(330, 100, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.progi_label.setFont(font)
        self.progi_label.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.progi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.progi_label.setObjectName("progi_label")
        self.aktualne_progi_btn = QtWidgets.QPushButton(self.page_5)
        self.aktualne_progi_btn.setGeometry(QtCore.QRect(330, 200, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.aktualne_progi_btn.setFont(font)
        self.aktualne_progi_btn.setStyleSheet("QPushButton#aktualne_progi_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#aktualne_progi_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#aktualne_progi_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.aktualne_progi_btn.setObjectName("aktualne_progi_btn")
        self.tempEdit = QtWidgets.QTextEdit(self.page_5)
        self.tempEdit.setGeometry(QtCore.QRect(220, 470, 201, 31))
        self.tempEdit.setObjectName("tempEdit")
        self.humEdit = QtWidgets.QTextEdit(self.page_5)
        self.humEdit.setGeometry(QtCore.QRect(490, 470, 201, 31))
        self.humEdit.setObjectName("humEdit")
        self.prog_temp = QtWidgets.QLabel(self.page_5)
        self.prog_temp.setGeometry(QtCore.QRect(190, 410, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.prog_temp.setFont(font)
        self.prog_temp.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.prog_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_temp.setObjectName("prog_temp")
        self.prog_hum = QtWidgets.QLabel(self.page_5)
        self.prog_hum.setGeometry(QtCore.QRect(460, 410, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.prog_hum.setFont(font)
        self.prog_hum.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.prog_hum.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_hum.setObjectName("prog_hum")
        self.zmiana_progi = QtWidgets.QLabel(self.page_5)
        self.zmiana_progi.setGeometry(QtCore.QRect(330, 300, 261, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zmiana_progi.setFont(font)
        self.zmiana_progi.setStyleSheet("color: rgba(46, 82, 101, 200);")
        self.zmiana_progi.setAlignment(QtCore.Qt.AlignCenter)
        self.zmiana_progi.setObjectName("zmiana_progi")
        self.confirm_temp_btn = QtWidgets.QPushButton(self.page_5)
        self.confirm_temp_btn.setGeometry(QtCore.QRect(250, 510, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirm_temp_btn.setFont(font)
        self.confirm_temp_btn.setStyleSheet("QPushButton#confirm_temp_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#confirm_temp_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#confirm_temp_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.confirm_temp_btn.setObjectName("confirm_temp_btn")
        self.confirm_hum_btn = QtWidgets.QPushButton(self.page_5)
        self.confirm_hum_btn.setGeometry(QtCore.QRect(530, 510, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.confirm_hum_btn.setFont(font)
        self.confirm_hum_btn.setStyleSheet("QPushButton#confirm_hum_btn{\n"
"background-color: rgba(46, 82, 101, 250);\n"
"color: rgba(200, 200, 200, 200);\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton#confirm_hum_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgba(46, 82, 101, 100);\n"
"background-position:calc(100% = 10px)center;\n"
"}\n"
"QPushButton#confirm_hum_btn:hover{\n"
"background-color: rgba(46, 82, 101, 200);\n"
"}\n"
"")
        self.confirm_hum_btn.setObjectName("confirm_hum_btn")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        '''!@brief Metoda odpowiadająca za tłumaczenie tekstu GUI.'''
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setPlaceholderText(_translate("MainWindow", "Nazwa użytkownika"))
        self.haslo.setPlaceholderText(_translate("MainWindow", "Hasło"))
        self.logo.setText(_translate("MainWindow", ""))
        self.login_btn.setText(_translate("MainWindow", "ZALOGUJ SIĘ"))
        self.exit_btn.setText(_translate("MainWindow", "X"))
        self.exit_btn_2.setText(_translate("MainWindow", "X"))
        self.logout_btn.setText(_translate("MainWindow", ""))
        self.menu_label.setText(_translate("MainWindow", "MENU"))
        self.chart_btn.setText(_translate("MainWindow", "Wykresy"))
        self.history_btn.setText(_translate("MainWindow", "Historia"))
        self.settings_btn.setText(_translate("MainWindow", "Ustawienia"))
        self.stany_czujnikow_label.setText(_translate("MainWindow", "STANY CZUJNIKÓW"))
        self.temp_label.setText(_translate("MainWindow", "Temperatura i Wilgotność"))
        self.sensor_btn.setText(_translate("MainWindow", "Stan czujnika"))
        self.exit_btn_3.setText(_translate("MainWindow", "X"))
        self.logout_btn_2.setText(_translate("MainWindow", ""))
        self.menu_label_2.setText(_translate("MainWindow", "MENU"))
        self.back_btn.setText(_translate("MainWindow", "Powrót"))
        self.wykresy_label.setText(_translate("MainWindow", "WYKRESY"))
        self.chart_sensor.setText(_translate("MainWindow", "Wykresy czujnika DHT11"))
        self.exit_btn_4.setText(_translate("MainWindow", "X"))
        self.logout_btn_3.setText(_translate("MainWindow", ""))
        self.menu_label_3.setText(_translate("MainWindow", "MENU"))
        self.back_btn_2.setText(_translate("MainWindow", "Powrót"))
        self.historia_label.setText(_translate("MainWindow", "Historia"))
        self.browse_btn.setText(_translate("MainWindow", "Przeglądaj alarmy"))
        self.exit_btn_5.setText(_translate("MainWindow", "X"))
        self.logout_btn_4.setText(_translate("MainWindow", ""))
        self.menu_label_4.setText(_translate("MainWindow", "MENU"))
        self.back_btn_3.setText(_translate("MainWindow", "Powrót"))
        self.ustawienia_label.setText(_translate("MainWindow", "USTAWIENIA"))
        self.progi_label.setText(_translate("MainWindow", "PROGI ALARMOWE"))
        self.aktualne_progi_btn.setText(_translate("MainWindow", "Aktualne progi alarmowe"))
        self.prog_temp.setText(_translate("MainWindow", "Temperatura"))
        self.prog_hum.setText(_translate("MainWindow", "Wilgotność"))
        self.zmiana_progi.setText(_translate("MainWindow", "ZMIANA PROGÓW"))
        self.confirm_temp_btn.setText(_translate("MainWindow", "Potwierdź"))
        self.confirm_hum_btn.setText(_translate("MainWindow", "Potwierdź"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
